/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

// const awsmobile = {
//     "aws_project_region": "us-east-2",
//     "aws_cognito_identity_pool_id": "us-east-2:9288cd7b-0e0c-46d1-8352-1721f17cb8be",
//     "aws_cognito_region": "us-east-2",
//     "aws_user_pools_id": "us-east-2_tkumWyqDQ",
//     "aws_user_pools_web_client_id": "38oh0vkd23uncncipolh8f13cf",
//     "oauth": {},
//     "aws_appsync_graphqlEndpoint": "https://gju2mg2ntvashhf4jlptky47ou.appsync-api.us-east-2.amazonaws.com/graphql",
//     "aws_appsync_region": "us-east-2",
//     "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
//     "aws_user_files_s3_bucket": "petgenomang77a84b2aa5274bc3bc34706374a937b4224505-dev",
//     "aws_user_files_s3_bucket_region": "us-east-2"
// };


// export default awsmobile;
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:bf9bad89-3bb0-4a1e-8ca3-a938dce9a7d0",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_iLI39s0OB",
    "aws_user_pools_web_client_id": "mqtpv2o8ue9tr944cgfb6r5dg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ngpetgenomaaws04c39af5e7ab433e8ded87d9270a4818125216-pg",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://qnh74jqblfhidmem36f72rzusa.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;

