/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:9288cd7b-0e0c-46d1-8352-1721f17cb8be",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_tkumWyqDQ",
    "aws_user_pools_web_client_id": "38oh0vkd23uncncipolh8f13cf",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://gju2mg2ntvashhf4jlptky47ou.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "petgenomang77a84b2aa5274bc3bc34706374a937b4224505-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
